//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.24 at 11:02:00 AM AST 
//


package com.example.consumesoapwebservice1.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetIndividualWaselAddressResult" type="{http://yesser.gov.sa/SaudiPost/SPWaselAddressService/version/1.0}getIndividualWaselAddressResponseStructure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getIndividualWaselAddressResult"
})
@XmlRootElement(name = "GetIndividualWaselAddressResponse")
public class GetIndividualWaselAddressResponse {

    @XmlElement(name = "GetIndividualWaselAddressResult")
    protected GetIndividualWaselAddressResponseStructure getIndividualWaselAddressResult;

    /**
     * Gets the value of the getIndividualWaselAddressResult property.
     * 
     * @return
     *     possible object is
     *     {@link GetIndividualWaselAddressResponseStructure }
     *     
     */
    public GetIndividualWaselAddressResponseStructure getGetIndividualWaselAddressResult() {
        return getIndividualWaselAddressResult;
    }

    /**
     * Sets the value of the getIndividualWaselAddressResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetIndividualWaselAddressResponseStructure }
     *     
     */
    public void setGetIndividualWaselAddressResult(GetIndividualWaselAddressResponseStructure value) {
        this.getIndividualWaselAddressResult = value;
    }

}
