//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.24 at 11:02:00 AM AST 
//


package com.example.consumesoapwebservice1.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getIndividualWaselAddressResponseStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getIndividualWaselAddressResponseStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="getIndividualWaselAddressResponseDetailObject" type="{http://yefi.gov.sa/SaudiPost/WaselAddressSchema/xml/schemas/version1.0}WaselAddressesListStructure" minOccurs="0" form="unqualified"/&gt;
 *           &lt;element ref="{http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3}ServiceError" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getIndividualWaselAddressResponseStructure", namespace = "http://yesser.gov.sa/SaudiPost/SPWaselAddressService/version/1.0", propOrder = {
    "getIndividualWaselAddressResponseDetailObject",
    "serviceError"
})
public class GetIndividualWaselAddressResponseStructure {

    @XmlElement(namespace = "")
    protected WaselAddressesListStructure getIndividualWaselAddressResponseDetailObject;
    @XmlElement(name = "ServiceError", namespace = "http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3")
    protected CommonErrorStructure serviceError;

    /**
     * Gets the value of the getIndividualWaselAddressResponseDetailObject property.
     * 
     * @return
     *     possible object is
     *     {@link WaselAddressesListStructure }
     *     
     */
    public WaselAddressesListStructure getGetIndividualWaselAddressResponseDetailObject() {
        return getIndividualWaselAddressResponseDetailObject;
    }

    /**
     * Sets the value of the getIndividualWaselAddressResponseDetailObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaselAddressesListStructure }
     *     
     */
    public void setGetIndividualWaselAddressResponseDetailObject(WaselAddressesListStructure value) {
        this.getIndividualWaselAddressResponseDetailObject = value;
    }

    /**
     * Gets the value of the serviceError property.
     * 
     * @return
     *     possible object is
     *     {@link CommonErrorStructure }
     *     
     */
    public CommonErrorStructure getServiceError() {
        return serviceError;
    }

    /**
     * Sets the value of the serviceError property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonErrorStructure }
     *     
     */
    public void setServiceError(CommonErrorStructure value) {
        this.serviceError = value;
    }

}
