//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.24 at 11:02:00 AM AST 
//


package com.example.consumesoapwebservice1.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemChoiceType1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ItemChoiceType1"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CommercialRegistrationNumber"/&gt;
 *     &lt;enumeration value="LaborOfficeIdentity"/&gt;
 *     &lt;enumeration value="SevenHundredNumber"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ItemChoiceType1", namespace = "http://yesser.gov.sa/SaudiPost/SPWaselAddressService/version/1.0")
@XmlEnum
public enum ItemChoiceType1 {

    @XmlEnumValue("CommercialRegistrationNumber")
    COMMERCIAL_REGISTRATION_NUMBER("CommercialRegistrationNumber"),
    @XmlEnumValue("LaborOfficeIdentity")
    LABOR_OFFICE_IDENTITY("LaborOfficeIdentity"),
    @XmlEnumValue("SevenHundredNumber")
    SEVEN_HUNDRED_NUMBER("SevenHundredNumber");
    private final String value;

    ItemChoiceType1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ItemChoiceType1 fromValue(String v) {
        for (ItemChoiceType1 c: ItemChoiceType1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
