//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.24 at 11:02:00 AM AST 
//


package com.example.consumesoapwebservice1.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.consumesoapwebservice1.stubs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CommonErrorElement_QNAME = new QName("http://tempuri.org/", "commonErrorElement");
    private final static QName _ServiceError_QNAME = new QName("http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3", "ServiceError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.consumesoapwebservice1.stubs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCommercialWaselAddress }
     * 
     */
    public GetCommercialWaselAddress createGetCommercialWaselAddress() {
        return new GetCommercialWaselAddress();
    }

    /**
     * Create an instance of {@link GetCommercialWaselAddressResponse }
     * 
     */
    public GetCommercialWaselAddressResponse createGetCommercialWaselAddressResponse() {
        return new GetCommercialWaselAddressResponse();
    }

    /**
     * Create an instance of {@link GetCommercialWaselAddressResponseStructure }
     * 
     */
    public GetCommercialWaselAddressResponseStructure createGetCommercialWaselAddressResponseStructure() {
        return new GetCommercialWaselAddressResponseStructure();
    }

    /**
     * Create an instance of {@link CommonErrorStructure }
     * 
     */
    public CommonErrorStructure createCommonErrorStructure() {
        return new CommonErrorStructure();
    }

    /**
     * Create an instance of {@link GetIndividualWaselAddress }
     * 
     */
    public GetIndividualWaselAddress createGetIndividualWaselAddress() {
        return new GetIndividualWaselAddress();
    }

    /**
     * Create an instance of {@link GetIndividualWaselAddressResponse }
     * 
     */
    public GetIndividualWaselAddressResponse createGetIndividualWaselAddressResponse() {
        return new GetIndividualWaselAddressResponse();
    }

    /**
     * Create an instance of {@link GetIndividualWaselAddressResponseStructure }
     * 
     */
    public GetIndividualWaselAddressResponseStructure createGetIndividualWaselAddressResponseStructure() {
        return new GetIndividualWaselAddressResponseStructure();
    }

    /**
     * Create an instance of {@link WaselAddressesListStructure }
     * 
     */
    public WaselAddressesListStructure createWaselAddressesListStructure() {
        return new WaselAddressesListStructure();
    }

    /**
     * Create an instance of {@link WaselAddressStructure }
     * 
     */
    public WaselAddressStructure createWaselAddressStructure() {
        return new WaselAddressStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "commonErrorElement")
    public JAXBElement<CommonErrorStructure> createCommonErrorElement(CommonErrorStructure value) {
        return new JAXBElement<CommonErrorStructure>(_CommonErrorElement_QNAME, CommonErrorStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3", name = "ServiceError")
    public JAXBElement<CommonErrorStructure> createServiceError(CommonErrorStructure value) {
        return new JAXBElement<CommonErrorStructure>(_ServiceError_QNAME, CommonErrorStructure.class, null, value);
    }

}
