//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.24 at 11:02:00 AM AST 
//


package com.example.consumesoapwebservice1.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaselAddressStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaselAddressStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BuildingNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AdditionalNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="UnitNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="DistrictAreaArabic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DistrictAreaEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StreetNameArabic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StreetNameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CityNameArabic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CityNameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaselAddressStructure", namespace = "http://yefi.gov.sa/SaudiPost/WaselAddressSchema/xml/schemas/version1.0", propOrder = {
    "buildingNumber",
    "additionalNumber",
    "zipCode",
    "unitNumber",
    "districtAreaArabic",
    "districtAreaEnglish",
    "streetNameArabic",
    "streetNameEnglish",
    "cityNameArabic",
    "cityNameEnglish",
    "fullName"
})
public class WaselAddressStructure {

    @XmlElement(name = "BuildingNumber")
    protected int buildingNumber;
    @XmlElement(name = "AdditionalNumber")
    protected int additionalNumber;
    @XmlElement(name = "ZipCode")
    protected int zipCode;
    @XmlElement(name = "UnitNumber")
    protected Integer unitNumber;
    @XmlElement(name = "DistrictAreaArabic")
    protected String districtAreaArabic;
    @XmlElement(name = "DistrictAreaEnglish")
    protected String districtAreaEnglish;
    @XmlElement(name = "StreetNameArabic")
    protected String streetNameArabic;
    @XmlElement(name = "StreetNameEnglish")
    protected String streetNameEnglish;
    @XmlElement(name = "CityNameArabic")
    protected String cityNameArabic;
    @XmlElement(name = "CityNameEnglish")
    protected String cityNameEnglish;
    @XmlElement(name = "FullName")
    protected String fullName;

    /**
     * Gets the value of the buildingNumber property.
     * 
     */
    public int getBuildingNumber() {
        return buildingNumber;
    }

    /**
     * Sets the value of the buildingNumber property.
     * 
     */
    public void setBuildingNumber(int value) {
        this.buildingNumber = value;
    }

    /**
     * Gets the value of the additionalNumber property.
     * 
     */
    public int getAdditionalNumber() {
        return additionalNumber;
    }

    /**
     * Sets the value of the additionalNumber property.
     * 
     */
    public void setAdditionalNumber(int value) {
        this.additionalNumber = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     */
    public int getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     */
    public void setZipCode(int value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the unitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnitNumber() {
        return unitNumber;
    }

    /**
     * Sets the value of the unitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnitNumber(Integer value) {
        this.unitNumber = value;
    }

    /**
     * Gets the value of the districtAreaArabic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictAreaArabic() {
        return districtAreaArabic;
    }

    /**
     * Sets the value of the districtAreaArabic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictAreaArabic(String value) {
        this.districtAreaArabic = value;
    }

    /**
     * Gets the value of the districtAreaEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictAreaEnglish() {
        return districtAreaEnglish;
    }

    /**
     * Sets the value of the districtAreaEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictAreaEnglish(String value) {
        this.districtAreaEnglish = value;
    }

    /**
     * Gets the value of the streetNameArabic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNameArabic() {
        return streetNameArabic;
    }

    /**
     * Sets the value of the streetNameArabic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNameArabic(String value) {
        this.streetNameArabic = value;
    }

    /**
     * Gets the value of the streetNameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNameEnglish() {
        return streetNameEnglish;
    }

    /**
     * Sets the value of the streetNameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNameEnglish(String value) {
        this.streetNameEnglish = value;
    }

    /**
     * Gets the value of the cityNameArabic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityNameArabic() {
        return cityNameArabic;
    }

    /**
     * Sets the value of the cityNameArabic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityNameArabic(String value) {
        this.cityNameArabic = value;
    }

    /**
     * Gets the value of the cityNameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityNameEnglish() {
        return cityNameEnglish;
    }

    /**
     * Sets the value of the cityNameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityNameEnglish(String value) {
        this.cityNameEnglish = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

}
