//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.24 at 11:02:00 AM AST 
//


package com.example.consumesoapwebservice1.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaselAddressesListStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaselAddressesListStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WaselAddress" type="{http://yefi.gov.sa/SaudiPost/WaselAddressSchema/xml/schemas/version1.0}WaselAddressStructure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaselAddressesListStructure", namespace = "http://yefi.gov.sa/SaudiPost/WaselAddressSchema/xml/schemas/version1.0", propOrder = {
    "waselAddress"
})
public class WaselAddressesListStructure {

    @XmlElement(name = "WaselAddress")
    protected List<WaselAddressStructure> waselAddress;

    /**
     * Gets the value of the waselAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waselAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaselAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaselAddressStructure }
     * 
     * 
     */
    public List<WaselAddressStructure> getWaselAddress() {
        if (waselAddress == null) {
            waselAddress = new ArrayList<WaselAddressStructure>();
        }
        return this.waselAddress;
    }

}
